### ISSUE TITLE
The spider easy can't work in Chapter 8

### ISSUE THREAD

**Issue by polar9527** [scalingexcellence/scrapybook#29]
Page 138 
When I ran the script "scrapy crawl easy -s CLOSESPIDER_ITEMCOUNT=90", I got this :

> root@dev:~/book/ch08/properties# scrapy crawl easy -s CLOSESPIDER_ITEMCOUNT=90
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 109, in execute
    settings = get_project_settings()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/project.py", line 60, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/\_\_init\_\_.py", line 108, in setmodule
    module = import_module(module)
  File "/usr/lib/python2.7/importlib/\_\_init\_\_.py", line 37, in import_module
   \_\_import\_\_(name)
ImportError: No module named properties.settings

---------------------------------------------------------------------------------
The file properties.settings was really in  the  directory, I don't know why it said the file can't be found.

can you help me?
thanks -John

**Comment by polar9527** [comment]
I sovled this problem, It is because there isn't a \_\_init\_\_.py file in you source code in the directory of ch08/properties/properties

**Comment by lookfwd** [comment]
Well done. Thanks!
