### ISSUE TITLE
when I run 'vagrant up --no-parallel', error:/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/providers/docker/communicator.rb:50:in `execute': wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by oliver29520** [scalingexcellence/scrapybook#76]
Is the cause of this error to use the new vagrant version? Has anyone encountered the same problem?

vagrant up --no-parallel
Bringing machine 'web' up with 'docker' provider...
Bringing machine 'spark' up with 'docker' provider...
Bringing machine 'es' up with 'docker' provider...
Bringing machine 'redis' up with 'docker' provider...
Bringing machine 'mysql' up with 'docker' provider...
Bringing machine 'scrapyd1' up with 'docker' provider...
Bringing machine 'scrapyd2' up with 'docker' provider...
Bringing machine 'scrapyd3' up with 'docker' provider...
Bringing machine 'dev' up with 'docker' provider...
==> web: Docker host is required. One will be created if necessary...
    web: Docker host VM is already ready.
==> spark: Docker host is required. One will be created if necessary...
    spark: Docker host VM is already ready.
==> spark: Syncing folders to the host VM...
    docker-provider: Mounting shared folders...
    docker-provider: /var/lib/docker/docker_f3af71afb7bbe4a15a1efe8e02b1aba3 => /root/new_scrapybook/scrapybook
==> spark: Warning: When using a remote Docker host, forwarded ports will NOT be
==> spark: immediately available on your machine. They will still be forwarded on
==> spark: the remote machine, however, so if you have a way to access the remote
==> spark: machine, then you should be able to access those ports there. This is
==> spark: not an error, it is only an informational message.
==> spark: Fixed port collision for 22 => 2222. Now on port 2200.
==> spark: Creating the container...
    spark:   Name: spark
    spark:  Image: scrapybook/spark
    spark: Volume: /var/lib/docker/docker_f3af71afb7bbe4a15a1efe8e02b1aba3:/root/book
    spark:   Port: 2134:21
    spark:   Port: 60000:60000
    spark:   Port: 60001:60001
    spark:   Port: 60002:60002
    spark:   Port: 60003:60003
    spark:   Port: 60004:60004
    spark:   Port: 60005:60005
    spark:   Port: 60006:60006
    spark:   Port: 60007:60007
    spark:   Port: 60008:60008
    spark:   Port: 60009:60009
    spark:  
    spark: Container created: f125d0dd0296f71e
==> spark: Starting container...
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/providers/docker/communicator.rb:50:in `execute': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/providers/docker/communicator.rb:121:in `test'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/guests/atomic/guest.rb:10:in `detect?'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/capability_host.rb:151:in `block (2 levels) in autodetect_capability_host'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/capability_host.rb:146:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/capability_host.rb:146:in `block in autodetect_capability_host'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/capability_host.rb:145:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/capability_host.rb:145:in `autodetect_capability_host'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/capability_host.rb:39:in `initialize_capabilities!'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/guest.rb:39:in `detect!'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/machine.rb:283:in `guest'

**Comment by oliver29520** [comment]
there is the same issue with the latest vagrant 2.4.3.
